package blcs.lwb.utils.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import blcs.lwb.utils.bean.GreenDao;

import blcs.lwb.utils.greendao.GreenDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenDaoDaoConfig;

    private final GreenDaoDao greenDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenDaoDaoConfig = daoConfigMap.get(GreenDaoDao.class).clone();
        greenDaoDaoConfig.initIdentityScope(type);

        greenDaoDao = new GreenDaoDao(greenDaoDaoConfig, this);

        registerDao(GreenDao.class, greenDaoDao);
    }
    
    public void clear() {
        greenDaoDaoConfig.clearIdentityScope();
    }

    public GreenDaoDao getGreenDaoDao() {
        return greenDaoDao;
    }

}
